sudo: true

dist: xenial

install:
  - sudo apt-get -y update
  - sudo apt-get -y install octave
  - sudo apt-get -y install git
  - git clone https://github.com/MOcov/MOcov.git
  - cd MOcov && make install && cd ..

script:
  - bash run.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)
